POST http://localhost:9080/rest-service/api/stringprocess/convert HTTP/1.1
content-type: application/json

{
    "input_string":"Hello     World   "
}

###

GET  http://localhost:9080/rest-service/api/stringprocess/ping HTTP/1.1
content-type: application/json
