/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.utilities;

import java.util.List;
import org.apache.commons.text.WordUtils;

public class StringUtils {
    public static String join(List<String> source) {
        return JoinUtils.join(source);
    }

    public static List<String> split(String source) {
        return SplitUtils.split(source);
    }

    public static StringProcess process(StringProcess r) {
        List<String> tokens;
        tokens = split(r.input);
        String result = join(tokens);
        r.output = WordUtils.capitalize(result);
        return r;
    }
}
